name: Run News Summary Script
#triggering rerun

on:
  workflow_dispatch:
  schedule:
    - cron: '44 13 * * *'   # Mondays at 9:05am UTC
    - cron: '5 9 * * 4'   # Thursdays at 9:05am UTC

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          CLIENT_ID: ${{secrets.CLIENT_ID}}
          TENANT_ID: ${{secrets.TENANT_ID}}
          CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
          OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
          SHARED_MAILBOX: ${{secrets.SHARED_MAILBOX}}
          EMAIL_RECIPIENTS: ${{secrets.EMAIL_RECIPIENTS}}
          SENDER_EMAIL: ${{secrets.SENDER_EMAIL}}
        run: python main.py
